title: Add a full width section with title and text
hero_image: images/banner.png
description: Add a full width section with title and text
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Add a full width section with title and text
