title: Ajouter une section pleine largeur avec le titre et le texte
hero_image: images/banner.png
description: Ajoute une section pleine largeur avec le titre et le texte.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Ajouter une section pleine largeur avec le titre et le texte
